#!/usr/bin/env python3
"""
Generate an HTML compliance gap report from fincompliance output.
This is the artifact you send to credit union compliance officers.
"""

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def run_fincompliance(file_path: str) -> dict:
    """Run fincompliance and capture JSON output."""
    result = subprocess.run(
        ["python3", "-m", "fincompliance.cli", file_path, "--format", "json"],
        capture_output=True,
        text=True,
        cwd=str(Path(__file__).parent.parent),
    )
    return json.loads(result.stdout) if result.stdout.strip() else {}


def generate_html_report(data: dict, institution_name: str = "Sample Institution") -> str:
    """Generate a professional HTML gap report."""
    doc_findings = data.get("document_findings", [])
    vale_findings = data.get("vale_findings", {})

    errors = [f for f in doc_findings if f["level"] == "error"]
    warnings = [f for f in doc_findings if f["level"] == "warning"]
    suggestions = [f for f in doc_findings if f["level"] == "suggestion"]

    vale_errors = 0
    vale_warnings = 0
    vale_suggestions = 0
    vale_items = []
    for filepath, alerts in vale_findings.items():
        for a in alerts:
            level = a.get("Severity", "warning").lower()
            if level == "error":
                vale_errors += 1
            elif level == "warning":
                vale_warnings += 1
            else:
                vale_suggestions += 1
            vale_items.append({
                "line": a.get("Line", 0),
                "level": level,
                "check": a.get("Check", ""),
                "message": a.get("Message", ""),
            })

    total_errors = len(errors) + vale_errors
    total_warnings = len(warnings) + vale_warnings
    total_suggestions = len(suggestions) + vale_suggestions

    score = max(0, 100 - (total_errors * 10) - (total_warnings * 3) - (total_suggestions * 1))

    score_color = "#22c55e" if score >= 80 else "#eab308" if score >= 50 else "#ef4444"

    findings_html = ""
    for f in doc_findings:
        icon = {"error": "X", "warning": "!", "suggestion": "i"}.get(f["level"], "?")
        color = {"error": "#ef4444", "warning": "#eab308", "suggestion": "#3b82f6"}.get(f["level"], "#666")
        citation = f' <span style="color:#888">({f["citation"]})</span>' if f.get("citation") else ""
        findings_html += f'''
        <div style="border-left:4px solid {color}; padding:8px 12px; margin:8px 0; background:#f9f9f9">
            <strong style="color:{color}">[{f["level"].upper()}]</strong> {f["rule"]}: {f["message"]}{citation}
        </div>'''

    for item in vale_items:
        color = {"error": "#ef4444", "warning": "#eab308", "suggestion": "#3b82f6"}.get(item["level"], "#666")
        findings_html += f'''
        <div style="border-left:4px solid {color}; padding:8px 12px; margin:8px 0; background:#f9f9f9">
            <strong style="color:{color}">[{item["level"].upper()}]</strong> Line {item["line"]}: {item["message"]}
        </div>'''

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Compliance Documentation Gap Report — {institution_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; line-height: 1.6; }}
        h1 {{ font-size: 24px; margin-bottom: 4px; }}
        h2 {{ font-size: 18px; color: #333; margin-top: 32px; border-bottom: 1px solid #e5e5e5; padding-bottom: 8px; }}
        .subtitle {{ color: #666; font-size: 14px; margin-bottom: 32px; }}
        .score-box {{ text-align: center; padding: 24px; border-radius: 8px; background: #f8f8f8; margin: 24px 0; }}
        .score {{ font-size: 48px; font-weight: bold; }}
        .summary-grid {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin: 24px 0; }}
        .summary-card {{ text-align: center; padding: 16px; border-radius: 8px; }}
        .summary-card .number {{ font-size: 32px; font-weight: bold; }}
        .summary-card .label {{ font-size: 12px; color: #666; text-transform: uppercase; }}
        .footer {{ margin-top: 48px; padding-top: 24px; border-top: 1px solid #e5e5e5; font-size: 13px; color: #888; }}
        .cta {{ background: #1a1a1a; color: white; padding: 16px 24px; border-radius: 8px; text-align: center; margin: 32px 0; }}
        .cta a {{ color: #60a5fa; }}
    </style>
</head>
<body>
    <h1>Compliance Documentation Gap Report</h1>
    <p class="subtitle">Prepared for {institution_name} | {datetime.now().strftime('%B %d, %Y')} | Generated by FinCompliance</p>

    <div class="score-box">
        <div class="score" style="color:{score_color}">{score}/100</div>
        <div>Compliance Documentation Score</div>
    </div>

    <div class="summary-grid">
        <div class="summary-card" style="background:#fef2f2">
            <div class="number" style="color:#ef4444">{total_errors}</div>
            <div class="label">Errors (must fix)</div>
        </div>
        <div class="summary-card" style="background:#fefce8">
            <div class="number" style="color:#eab308">{total_warnings}</div>
            <div class="label">Warnings (should fix)</div>
        </div>
        <div class="summary-card" style="background:#eff6ff">
            <div class="number" style="color:#3b82f6">{total_suggestions}</div>
            <div class="label">Suggestions</div>
        </div>
    </div>

    <h2>Detailed Findings</h2>
    {findings_html}

    <h2>What These Findings Mean</h2>
    <p>Each <strong style="color:#ef4444">error</strong> represents a gap that NCUA or OCC examiners are likely to cite as a finding during your next examination. Errors include missing required policy elements, prohibited language suggesting incomplete compliance, and structural issues that prevent examiner review.</p>
    <p><strong style="color:#eab308">Warnings</strong> are issues that weaken your documentation but may not result in a formal finding. These include vague language, unspecified timeframes, and unassigned responsibilities that make policies harder to enforce and audit.</p>

    <h2>Recommended Next Steps</h2>
    <ol>
        <li>Address all <strong>errors</strong> before your next examination cycle</li>
        <li>Review <strong>warnings</strong> with your compliance officer or committee</li>
        <li>Consider a full documentation suite review across all compliance policies</li>
    </ol>

    <div class="cta">
        <p><strong>Want a full compliance documentation audit?</strong></p>
        <p>FinCompliance checks your entire policy suite against BSA/AML, SOX, PCI-DSS, GLBA, and NCUA requirements. Get a complete gap analysis with specific remediation steps.</p>
        <p>Contact: <a href="mailto:bipinrimal314@gmail.com">bipinrimal314@gmail.com</a> | <a href="https://github.com/BipinRimal314/comply">github.com/BipinRimal314/comply</a></p>
    </div>

    <div class="footer">
        <p>This report was generated by FinCompliance v0.1.0 — the first open-source compliance documentation linter for financial institutions. The analysis covers document structure, regulatory language, required elements, and policy completeness. It is not a substitute for legal or compliance advice.</p>
        <p>Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
    </div>
</body>
</html>"""


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_report.py <document.md> [institution_name]")
        sys.exit(1)

    file_path = sys.argv[1]
    institution_name = sys.argv[2] if len(sys.argv) > 2 else "Sample Institution"

    data = run_fincompliance(file_path)
    html = generate_html_report(data, institution_name)

    output_path = Path(file_path).stem + "_gap_report.html"
    with open(output_path, "w") as f:
        f.write(html)
    print(f"Report generated: {output_path}")


if __name__ == "__main__":
    main()
